### ISSUE TITLE
In which window or image have i to press 'q' ?

### ISSUE THREAD

**Issue by jonashuberts** [CallMeRZIBI/Forza-autopilot#1]
I would like to stop the data_collection script, but I don't know in which window or image I have to press 'q'.
And my data_collections script is also saving no data but the session folder is always created.

**Comment by CallMeRZIBI** [comment]
You have to use 'q' in the image viewer that's opened. I will update the README as soon as I get home, so don't close this issue.

**Comment by jonashuberts** [comment]
Thank you for your quick response. 
Unfortunately, I don't have an image viewer, just the Forza Horizon 4 window and the output of the script, which shows the keys that were pressed.

**Comment by CallMeRZIBI** [comment]
Isn't it hidden under forza window?

**Comment by jonashuberts** [comment]
I don't think so, because it's not displayed in the taskbar either

**Comment by CallMeRZIBI** [comment]
Then try to update all Python libraries. And if that won't fix it I will look at it home once I get here.

**Comment by jonashuberts** [comment]
Yes, it worked for me to update the libraries, I hadn't the right versions of them. 
And I also found out that Python >= 3.9.x doesn't work with the script yet.

I have created a requirements.txt which I have added to this post to avoid further errors like this. 
Very much thank you for your help.

[requirements.txt](https://github.com/CallMeRZIBI/Forza-autopilot/files/6728122/requirements.txt)
